# Generated by Django 4.2.7 on 2023-11-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0005_remove_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreset',
            name='decimal_score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='scoreset',
            name='int_score',
            field=models.IntegerField(null=True),
        ),
    ]
