# Generated by Django 4.2.7 on 2023-11-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0006_scoreset_decimal_score_scoreset_int_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreset',
            name='total_inners',
            field=models.IntegerField(null=True),
        ),
    ]
