# Generated by Django 4.2.7 on 2023-11-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0007_scoreset_total_inners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreset',
            name='decimal_score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='scoreset',
            name='int_score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='scoreset',
            name='total_inners',
            field=models.IntegerField(),
        ),
    ]
