# Generated by Django 4.2.7 on 2023-11-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0008_alter_scoreset_decimal_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoretable',
            name='node_count',
            field=models.IntegerField(null=True),
        ),
    ]
