# Generated by Django 4.2.7 on 2023-11-30 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0009_scoretable_node_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scoretable',
            old_name='node_count',
            new_name='shots_count',
        ),
    ]
