# Generated by Django 4.2.7 on 2023-12-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0010_rename_node_count_scoretable_shots_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreset',
            name='nbr',
            field=models.IntegerField(default=1),
        ),
    ]
