name: Django all tests

on:
    push:
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Build the Docker image
              run: docker compose up -d --build

            - name: Wait for DB
              run: sleep 10 # Wait for the database to start up

            - name: Make Migrations
              run: docker-compose run web python3 manage.py makemigrations

            - name: Migrate
              run: docker-compose run web python3 manage.py migrate

            - name: Run tests
              run: docker-compose run web python3 manage.py test
