name: Django all tests

on:
    push:
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Build the Docker image
              run: docker-compose up --build -d

            - name: Migrate
              run: docker-compose run web python3 manage.py migrate

            - name: Run tests
              run: docker-compose run web python3 manage.py test
