name: Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      - docker

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build and run Docker Compose
      run: |
        docker-compose up -d --build
        docker-compose ps
