name: Django Test

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and run Docker Compose
        run: docker-compose up -d

      - name: Wait for services to start
        run: docker-compose exec -T web sh -c 'while ! nc -z db 5432; do sleep 1; done;'

      - name: Run tests
        run: docker-compose exec web python3 manage.py test

      - name: Stop Docker Compose
        run: docker-compose down
