name: Django Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d
          while [ ! -f "manage.py" ]; do
            sleep 1
          done
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432

      - name: Wait for Django to be ready
        run: |
          while true; do
            docker-compose exec web python3 manage.py check && break
            sleep 5
          done

      - name: Run Django Tests
        run: docker-compose exec web python3 manage.py test
