name: Django Test

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow on

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      run: docker-compose -f docker-compose.yml up -d

    #- name: Wait for services to start
    #  run: docker-compose -f docker-compose.yml exec web bash -c 'while ! python3 manage.py check; do sleep 1; done'

    - name: Run Tests
      run: docker-compose -f docker-compose.yml exec web python3 manage.py test

    - name: Stop Docker Compose
      run: docker-compose -f docker-compose.yml down
